version: '3.7'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: examportal_db
      POSTGRES_USER: examportal_user
      POSTGRES_PASSWORD: examportal_pass
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"

volumes:
  postgres_data: