# Generated by Django 4.2.3 on 2025-06-16 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_view_manage_tests', 'Can view Manage Tests'), ('can_view_manage_users', 'Can view Manage Users'), ('can_view_manage_questions', 'Can view Manage Questions'), ('can_view_general_test_generation', 'Can view General-Test Generation'), ('can_view_technical_test_generation', 'Can view Technical-Test Generation'), ('can_view_manage_instructions', 'Can view Manage Instructions'), ('can_view_view_results', 'Can view View Results'), ('can_view_manage_qr', 'Can view Manage QR'), ('can_view_manage_configurations', 'Can view Manage Configurations')],
            },
        ),
    ]
