# Generated by Django 4.2.3 on 2026-10-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Role_based_Access', '0002_employee_delete_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='accessible_modules',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
