"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os, random, string
from pathlib import Path
from dotenv import load_dotenv
from django.contrib.messages import constants as message_constants
load_dotenv()  # take environment variables from .env.

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    SECRET_KEY = ''.join(random.choice( string.ascii_lowercase  ) for i in range( 32 ))

# Render Deployment Code
#DEBUG = 'RENDER' not in os.environ
DEBUG = False
#DEBUG = True

ALLOWED_HOSTS = ['localhost','127.0.0.1','192.168.1.53','192.168.1.50', '49.249.160.198', '13.232.128.222','registration.intelligenzit.com', 'onlinetestzone.com','183.82.6.191', '*']

RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:    
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# Application definition
MESSAGE_TAGS = {
    message_constants.DEBUG: 'secondary',
    message_constants.INFO: 'info',
    message_constants.SUCCESS: 'success',
    message_constants.WARNING: 'warning',
    message_constants.ERROR: 'danger',  # map "error" → "danger"
}
INSTALLED_APPS = [
    #"django_prometheus",
    'admin_material.apps.AdminMaterialDashboardConfig',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'questions.apps.QuestionsConfig',
    "home",
    "Exam_dashboard",
    "widget_tweaks",
    "qr_generator",
    "config_keys",
    "Role_based_Access",
    "user_invite",
    "email_scheduler",
    'django_cron',
    'django_user_agents',

]

MIDDLEWARE = [
    #"django_prometheus.middleware.PrometheusBeforeMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django_user_agents.middleware.UserAgentMiddleware",
    "questions.middleware.QuestionsAppAuthMiddleware",
    "qr_generator.middleware.QRGeneratorAppAuthMiddleware",
    "Role_based_Access.middleware.PermissionMiddleware",
    "core.middleware.restrict_public.RestrictPublicAccessMiddleware",
    #"django_prometheus.middleware.PrometheusAfterMiddleware",
    # "core.middleware.user_logging_middleware.UserLoggingMiddleware",
    #"core.middleware.user_logging_middleware.UserRequestLoggingMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
                    os.path.join(BASE_DIR, 'core', 'templates'),
                    os.path.join(BASE_DIR, 'home', 'users', 'templates'), # ✅ Added this line
                    os.path.join(BASE_DIR, 'home', 'templates'), 
                    os.path.join(BASE_DIR, 'email_scheduler', 'templates'), # ✅ Added this line
                    # os.path.join(BASE_DIR, 'Exam_dashboard', 'templates'),  # ✅ Added this line
                ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"
# AUTH_USER_MODEL='home.Users'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DB_ENGINE   = os.getenv('DB_ENGINE'   , None)
DB_USERNAME = os.getenv('DB_USERNAME' , None)
DB_PASS     = os.getenv('DB_PASS'     , None)
DB_HOST     = os.getenv('DB_HOST'     , None)
DB_PORT     = os.getenv('DB_PORT'     , None)
DB_NAME     = os.getenv('DB_NAME'     , None)
print("DB_USERNAME:", os.getenv('DB_USERNAME'))
print("DB_HOST:", os.getenv('DB_HOST'))
print("DB_PASS:",os.getenv('DB_PASS'))


if DB_ENGINE and DB_NAME and DB_USERNAME:
    DATABASES = { 
    'default': {
        'ENGINE'  : 'django.db.backends.' + DB_ENGINE, 
        'NAME'    : DB_NAME,
        'USER'    : DB_USERNAME,
        'PASSWORD': DB_PASS,
        'HOST'    : DB_HOST,
        'PORT'    : DB_PORT,
        }, 
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': 'db.sqlite3',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # where your custom CSS is
    os.path.join(BASE_DIR, 'Exam_dashboard', 'static'),  # App-specific static directory
      # App-specific static directory
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

#if not DEBUG:
#    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_REDIRECT_URL = '/'
LOGIN_URL = '/admin/login/'  # Added to redirect to admin login
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# MEDIA_ROOT = os.path.join(BASE_DIR, 'users_logs')

EMAIL_HOST_USER     = "registrations@intelligenzit.com"
EMAIL_HOST_PASSWORD     = "lzfkcfjzdnkjdmvt"

# New EmailId
# EMAIL_HOST_USER     = "registrations1@intelligenzit.com"
# EMAIL_HOST_PASSWORD     = "byvldghkkbcmdmdh"

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.office365.com'  # or your email host
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = EMAIL_HOST_USER
EMAIL_HOST_PASSWORD = EMAIL_HOST_PASSWORD
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

RECAPTCHA_SECRET_KEY = '6LcgVYsrAAAAAEMlQ8LsW7upUO3UMBylSYq7X-jL'

DATA_UPLOAD_MAX_MEMORY_SIZE = 104857600 #100MB

CSRF_TRUSTED_ORIGINS = [
    'https://registration.intelligenzit.com',
    'https://www.registration.intelligenzit.com',
    'http://www.registration.intelligenzit.com',
    'http://192.168.1.50:8863',
    'http://13.232.128.222:8000',
    'http://183.82.6.191:8000',
    'https://onlinetestzone.com',
    'https://*.onlinetestzone.com',
    'http://127.0.0.1:8000/metrics',
    'http://13.232.128.222:8000/metrics',
    'http://192.168.1.50:8863/metrics',
    'http://192.168.1.50:9090',
    'http://192.168.1.50:3000'
]

# settings.py

import os

# Ensure the logger directory exists
LOG_DIR = os.path.join(BASE_DIR, 'logger')  # BASE_DIR is typically defined in settings.py
os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'console_like': {
            # Mimic the console output format of manage.py runserver
            'format': '[{asctime}] {message}',
            'style': '{',
            'datefmt': '%d/%b/%Y %H:%M:%S',  # Match runserver's date format
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',  # Use INFO to capture runserver's default output
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'output.log'),  # Save logs in logger/output.log
            'formatter': 'console_like',
            'mode': 'a',  # Append mode, like >>
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 3,  # Keep up to 3 backup files
        },
    },
    'loggers': {
        'django.server': {  # Specifically capture runserver logs
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': False,  # Prevent duplicate logging
        },
        'django': {  # Capture other Django logs
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': False,
        },
        '': {  # Root logger for custom apps
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

CRON_CLASSES = [
    "email_scheduler.cron.SendScheduledEmailsCronJob",
]


DJANGO_CRON_LOG_LEVEL = 'DEBUG'
DJANGO_CRON_LOG_TRACEBACK = True

GEOIP_PATH = BASE_DIR / "geoip"   # path where GeoLite2-City.mmdb is stored


