# Generated by Django 4.2.3 on 2026-10-06 20:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='question',
            name='specialisation_name',
            field=models.CharField(choices=[('C++', 'C++'), ('Java', 'Java'), ('Python', 'Python')], default='Not Applicable', max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='highest_qualification_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
