from django.core.management.base import BaseCommand
from django.utils import timezone
from config_keys.models import ConfigKeys
from datetime import datetime

class Command(BaseCommand):
    help = 'Seeds the config_keys table with initial data if not exists'

    def handle(self, *args, **kwargs):
        current_year = datetime.now().year  # Dynamically set the current year (2025)

        # Define initial config_keys data
        config_keys_data = [
            {
                'keys': f'programming_languages_{current_year}',
                'values': f'Programming Languages {current_year}',
                'identifier': f'programming_languages_{current_year}',
                'short_codes': None,
                'year': current_year,
                'created_date': datetime.strptime('2025-06-11 19:31:21.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'updated_date': datetime.strptime('2025-06-11 19:31:28.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'deleted': False,
            },
            {
                'keys': f'primary_skills_{current_year}',
                'values': f'Primary Skills {current_year}',
                'identifier': f'primary_skills_{current_year}',
                'short_codes': None,
                'year': current_year,
                'created_date': datetime.strptime('2025-07-11 16:32:00.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'updated_date': datetime.strptime('2025-07-11 16:32:00.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'deleted': False,
            },
            {
                'keys': f'gt_easy_questions_{current_year}',
                'values': f'Number of General-Test Easy Questions {current_year}',
                'identifier': f'gt_easy_questions_{current_year}',
                'short_codes': None,
                'year': current_year,
                'created_date': datetime.strptime('2025-06-11 19:31:57.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'updated_date': datetime.strptime('2025-06-11 19:31:57.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'deleted': False,
            },
            {
                'keys': f'gt_medium_questions_{current_year}',
                'values': f'Number of General-Test Medium Questions {current_year}',
                'identifier': f'gt_medium_questions_{current_year}',
                'short_codes': None,
                'year': current_year,
                'created_date': datetime.strptime('2025-06-11 19:31:57.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'updated_date': datetime.strptime('2025-06-11 19:31:57.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'deleted': False,
            },
            {
                'keys': f'gt_hard_questions_{current_year}',
                'values': f'Number of General-Test Hard Questions {current_year}',
                'identifier': f'gt_hard_questions_{current_year}',
                'short_codes': None,
                'year': current_year,
                'created_date': datetime.strptime('2025-06-11 19:36:57.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'updated_date': datetime.strptime('2025-06-11 19:36:57.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'deleted': False,
            },
            {
                'keys': f'gt_total_questions_{current_year}',
                'values': f'Number of General-Test Total Questions {current_year}',
                'identifier': f'gt_total_questions_{current_year}',
                'short_codes': None,
                'year': current_year,
                'created_date': datetime.strptime('2025-06-11 19:36:57.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'updated_date': datetime.strptime('2025-06-11 19:36:57.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'deleted': False,
            },
            {
                'keys': f'gt_duration_minutes_{current_year}',
                'values': f'General Test Duration {current_year}',
                'identifier': f'gt_duration_minutes_{current_year}',
                'short_codes': None,
                'year': current_year,
                'created_date': datetime.strptime('2025-06-11 19:54:59.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'updated_date': datetime.strptime('2025-06-11 19:54:59.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'deleted': False,
            },
            {
                'keys': f'gt_cutoff_pass_score_{current_year}',
                'values': f'General-Test CutOff Pass-Score {current_year}',
                'identifier': f'gt_cutoff_pass_score_{current_year}',
                'short_codes': None,
                'year': current_year,
                'created_date': datetime.strptime('2025-06-11 20:00:26.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'updated_date': datetime.strptime('2025-06-11 20:00:26.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'deleted': False,
            },
            {
                'keys': f'tt_coding_easy_questions_{current_year}',
                'values': f'Number of Technical-Test Easy Questions {current_year}',
                'identifier': f'tt_coding_easy_questions_{current_year}',
                'short_codes': None,
                'year': current_year,
                'created_date': datetime.strptime('2025-06-11 20:02:32.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'updated_date': datetime.strptime('2025-06-11 20:02:32.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'deleted': False,
            },
            {
                'keys': f'tt_coding_medium_questions_{current_year}',
                'values': f'Number of Technical-Test Medium Questions {current_year}',
                'identifier': f'tt_coding_medium_questions_{current_year}',
                'short_codes': None,
                'year': current_year,
                'created_date': datetime.strptime('2025-06-11 20:04:44.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'updated_date': datetime.strptime('2025-06-11 20:04:44.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'deleted': False,
            },
            {
                'keys': f'tt_coding_hard_questions_{current_year}',
                'values': f'Number of Technical-Test Hard Questions {current_year}',
                'identifier': f'tt_coding_hard_questions_{current_year}',
                'short_codes': None,
                'year': current_year,
                'created_date': datetime.strptime('2025-06-11 20:06:29.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'updated_date': datetime.strptime('2025-06-18 20:06:29.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'deleted': False,
            },
            {
                'keys': f'tt_total_questions_{current_year}',
                'values': f'Number of Technical-Test Total Questions {current_year}',
                'identifier': f'tt_total_questions_{current_year}',
                'short_codes': None,
                'year': current_year,
                'created_date': datetime.strptime('2025-06-11 20:07:25.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'updated_date': datetime.strptime('2025-06-11 20:07:25.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'deleted': False,
            },
            {
                'keys': f'tt_mcq_easy_questions_{current_year}',
                'values': f'Number of Technical-Test MCQ Easy Questions {current_year}',
                'identifier': f'tt_mcq_easy_questions_{current_year}',
                'short_codes': None,
                'year': current_year,
                'created_date': datetime.strptime('2025-06-11 20:02:32.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'updated_date': datetime.strptime('2025-06-11 20:02:32.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'deleted': False,
            },
            {
                'keys': f'tt_mcq_medium_questions_{current_year}',
                'values': f'Number of Technical-Test MCQ Medium Questions {current_year}',
                'identifier': f'tt_mcq_medium_questions_{current_year}',
                'short_codes': None,
                'year': current_year,
                'created_date': datetime.strptime('2025-06-11 20:04:44.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'updated_date': datetime.strptime('2025-06-11 20:04:44.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'deleted': False,
            },
            {
                'keys': f'tt_mcq_hard_questions_{current_year}',
                'values': f'Number of Technical-Test MCQ Hard Questions {current_year}',
                'identifier': f'tt_mcq_hard_questions_{current_year}',
                'short_codes': None,
                'year': current_year,
                'created_date': datetime.strptime('2025-06-11 20:06:29.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'updated_date': datetime.strptime('2025-06-18 20:06:29.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'deleted': False,
            },
            {
                'keys': f'tt_duration_minutes_{current_year}',
                'values': f'Technical Test Duration {current_year}',
                'identifier': f'tt_duration_minutes_{current_year}',
                'short_codes': None,
                'year': current_year,
                'created_date': datetime.strptime('2025-06-11 20:08:54.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'updated_date': datetime.strptime('2025-06-11 20:08:54.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'deleted': False,
            },
            {
                'keys': f'tt_cutoff_pass_score_{current_year}',
                'values': f'Technical-Test CutOff Pass-Score {current_year}',
                'identifier': f'tt_cutoff_pass_score_{current_year}',
                'short_codes': None,
                'year': current_year,
                'created_date': datetime.strptime('2025-06-11 20:10:09.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'updated_date': datetime.strptime('2025-06-11 20:10:09.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'deleted': False,
            },
            {
                'keys': f'photo_max_size_kb_{current_year}',
                'values': f'photo_max_size_kb {current_year}',
                'identifier': f'photo_max_size_kb_{current_year}',
                'short_codes': None,
                'year': current_year,
                'created_date': datetime.strptime('2025-06-11 20:10:09.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'updated_date': datetime.strptime('2025-06-11 20:10:09.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'deleted': False,
            },
            {
                'keys': f'resume_max_size_mb_{current_year}',
                'values': f'resume_max_size_mb {current_year}',
                'identifier': f'resume_max_size_mb_{current_year}',
                'short_codes': None,
                'year': current_year,
                'created_date': datetime.strptime('2025-06-11 20:10:09.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'updated_date': datetime.strptime('2025-06-11 20:10:09.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'deleted': False,
            },
            {
                'keys': f'id_proof_max_size_kb_{current_year}',
                'values': f'id_proof_max_size_kb {current_year}',
                'identifier': f'id_proof_max_size_kb_{current_year}',
                'short_codes': None,
                'year': current_year,
                'created_date': datetime.strptime('2025-06-11 20:10:09.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'updated_date': datetime.strptime('2025-06-11 20:10:09.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'deleted': False,
            },
            {
                'keys': f'certificate_max_size_mb_{current_year}',
                'values': f'certificate_max_size_mb {current_year}',
                'identifier': f'certificate_max_size_mb_{current_year}',
                'short_codes': None,
                'year': current_year,
                'created_date': datetime.strptime('2025-06-11 20:10:09.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'updated_date': datetime.strptime('2025-06-11 20:10:09.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'deleted': False,
            },
            {
                'keys': f'date_of_exam_{current_year}',
                'values': f'date of exam {current_year}',
                'identifier': f'date_of_exam_{current_year}',
                'short_codes': None,
                'year': current_year,
                'created_date': datetime.strptime('2025-06-19 22:00:00.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'updated_date': datetime.strptime('2025-06-19 22:00:00.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'deleted': False,
            },
            {
                'keys': f'time_of_exam_{current_year}',
                'values': f'time of exam {current_year}',
                'identifier': f'time_of_exam_{current_year}',
                'short_codes': None,
                'year': current_year,
                'created_date': datetime.strptime('2025-06-19 22:00:00.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'updated_date': datetime.strptime('2025-06-19 22:00:00.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'deleted': False,
            },
            {
                'keys': f'slot_timings_{current_year}',
                'values': f'slot {current_year}',
                'identifier': f'slot_timings_{current_year}',
                'short_codes': None,
                'year': current_year,
                'created_date': datetime.strptime('2025-06-19 22:00:00.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'updated_date': datetime.strptime('2025-06-19 22:00:00.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'deleted': False,
            },
            {
                'keys': f'contact_numbers_{current_year}',
                'values': f'contact numbers {current_year}',
                'identifier': f'contact_numbers_{current_year}',
                'short_codes': None,
                'year': current_year,
                'created_date': datetime.strptime('2025-06-19 22:53:00.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'updated_date': datetime.strptime('2025-06-19 22:53:00.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'deleted': False,
            },
            {
                'keys': f'recruitment_drive_dates_{current_year}',
                'values': f'recruitment drive dates {current_year}',
                'identifier': f'recruitment_drive_dates_{current_year}',
                'short_codes': None,
                'year': current_year,
                'created_date': datetime.strptime('2025-07-11 19:36:00.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'updated_date': datetime.strptime('2025-07-11 19:36:00.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'deleted': False,
            },
            {
                'keys': f'email_template_{current_year}',
                'values': f'email template {current_year}',
                'identifier': f'email_template_{current_year}',
                'short_codes': None,
                'year': current_year,
                'created_date': datetime.strptime('2025-07-18 15:00:00.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'updated_date': datetime.strptime('2025-07-18 15:00:00.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'deleted': False,
            },
            {
                'keys': f'suspicious_activity_count',
                'values': f'suspicious_activity_count',
                'identifier': f'suspicious_activity_count',
                'short_codes': None,
                'year': current_year,
                'created_date': datetime.strptime('2025-07-18 15:00:00.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'updated_date': datetime.strptime('2025-07-18 15:00:00.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'deleted': False,
            },
            {
                'keys': f'login_window_duration',
                'values': f'login_window_duration',
                'identifier': f'login_window_duration',
                'short_codes': None,
                'year': current_year,
                'created_date': datetime.strptime('2025-08-25 15:00:00.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'updated_date': datetime.strptime('2025-08-25 15:00:00.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'deleted': False,
            },
            {
                'key': f'freeze_Major_popup_timesec',
                'keys': f'freeze_Major_popup_timesec',
                'values': f'freeze_Major_popup_timesec',
                'identifier': f'freeze_Major_popup_timesec',
                'short_codes': None,
                'year': current_year,
                'created_date': datetime.strptime('2025-08-25 15:00:00.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'updated_date': datetime.strptime('2025-08-25 15:00:00.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'deleted': False,
            },
            {
                'key': f'freeze_Small_popup_timesec',
                'keys': f'freeze_Small_popup_timesec',
                'values': f'freeze_Small_popup_timesec',
                'identifier': f'freeze_Small_popup_timesec',
                'short_codes': None,
                'year': current_year,
                'created_date': datetime.strptime('2025-08-25 15:00:00.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'updated_date': datetime.strptime('2025-08-25 15:00:00.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'deleted': False,
            },
            {
                'key': f'suspicious_activity_majorpopup',
                'keys': f'suspicious_activity_majorpopup',
                'values': f'suspicious_activity_majorpopup',
                'identifier': f'suspicious_activity_majorpopup',
                'short_codes': None,
                'year': current_year,
                'created_date': datetime.strptime('2025-08-25 15:00:00.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'updated_date': datetime.strptime('2025-08-25 15:00:00.000000', '%Y-%m-%d %H:%M:%S.%f'),
                'deleted': False,
            }

        ]

        # Seed the data only if it doesn't exist
        for data in config_keys_data:
            if not ConfigKeys.objects.filter(keys=data['keys']).exists():
                ConfigKeys.objects.create(
                    keys=data['keys'],
                    values=data['values'],
                    identifier=data['identifier'],
                    short_codes=data['short_codes'],
                    year=data['year'],
                    created_date=data['created_date'],
                    updated_date=data['updated_date'],
                    deleted=data['deleted'],
                )
                self.stdout.write(self.style.SUCCESS(f"Added config_keys entry: {data['keys']}"))
            else:
                self.stdout.write(self.style.WARNING(f"ConfigKeys entry with keys '{data['keys']}' already exists"))

        self.stdout.write(self.style.SUCCESS('ConfigKeys seeding completed!'))